### ISSUE TITLE
[Bug]: server crash on startup 

### ISSUE THREAD

**Issue by CKY-** [Mrbysco/UndergroundVillages#1]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.1.0

### Mod version

1.18.2-1.0.0

### Java version

17

### Issue Description

A bug happened!
server fails to start here is the bug report 
https://pastebin.com/BXxb8Cki

**Comment by Mrbysco** [comment]
Fix has been uploaded (Forgot to upload it a week ago)
